specVersion: 0.2.0
name: hello
version: 0.0.4
description: This project can be use as a starting po...
repository: https://github.com/subquery/subql-starter
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala.polkawallet.io
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        #- handler: handleBlock
        #  kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: BalanceSet
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Deposit
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: DustLost
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Endowed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Reserved
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: ReserveRepatriated
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Slashed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Unreserved
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Withdraw
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balastakingnces
            method: Bonded
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Unbonded
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slashed
